// Conținutul cursului B/A, după notele lui Radu Diaconescu (octombrie 2023).
// Textul stă ascuns în pagină sub semnul întrebării; cursantul își scrie notele lui.

export type SubiectCurs = { cheie: string; titlu: string; continut: string[] }
export type ZiCurs = { zi: number; instructor: string; titlu: string; data: string; intro: string[]; subiecte: SubiectCurs[] }

export const CURS_B: ZiCurs[] = [
 {
  zi: 1, instructor: "Dr Florin Turcu", titlu: "Prim Ajutor pe mare", data: "16.10.2023",
  intro: ["‘In situatii de criza cel mai rau lucru care se poate intampla este sa nu faci nimic.’", "“The worst thing that you can do if a victim needs CPR is to do nothing”", "“There is no injury that you can do to the victim by doing CPR that can produce", "a more serious condition than death”.", "NASCO lifeguard textbook 2017"],
  subiecte: [
   { cheie: "z1-hipotermia", titlu: "Hipotermia", continut: [
    "- Scaderea temperaturii corpului",
    "- Poate duce la pierderea starii de constienta",
    "- Puls si respiratii slabe",
    "- Se poate recupera complet",
    "- Resuscitarea se face pana la incalzirea corpului",
    "- In hipotermie creierul este protejat fata de situatia unei anoxii",
    "- Daca ai cazut in apa rece nu continua sa innoti ci cauta sa iesi cat mai repede (nu te vei reincalzi",
    "innotand pt ca te vei epuiza mai inainte si daca agiti apa din jurul corpului ea va fi mereu rece)",
    "- 90% din pierderile de caldura se produc prin piele mai ales la nivelul capului si al gatului (deci",
    "necesara cagula sau ceva la gat)",
    "- Pierderile de caldura ale corpului scufundat in apa este de 25x mai mare decat in aer",
    "- Realfeel temp scade cu 1 grad la fiecare 4 km/h viteza vantului",
    "- Folia de aluminiu este inutila atunci cand corpul este ud!!",
    "o Scoti persoana din apa",
    "o Ii scoti hainele",
    "o Incalzesti intai trunchiul si nu membrele (pt sangele acolo e f rece si vei crea soc)",
    "o Nu incalzesti rapid prin imersie in apa calda",
    "o Imbraci cu haine uscate si patura peste",
    "o Ii dai bautura calda",
    "o Acoperi capul si gatul",
    "o Transport spital",
   ] },
   { cheie: "z1-prim-ajutor-resuscitare", titlu: "Prim ajutor – Resuscitare", continut: [
    "- Scopul este mentinerea vietii",
    "- Prevenirea agravarii situatiei",
    "- Usurarea suferintei",
    "- Cel mai bun tratament este PREVENTIA!!!",
    "Etape interventie: Asig masuri de siguranta – Alarma – prima ajutor – Ambulanta – Spital",
    "- Pe mare distantele sunt mari si timpul pana la obtinerea ajutorului poate fi foarte mare",
    "- Mesaj PAN PAN pe canalul 16 (May Day sunt mesaje cand iti e pusa viata in pericol dar legate",
    "de siguranta navei)",
    "PAN PAN / PAN PAN / PAN PAN",
    "This is ………………………………….",
    "My position is ……………………….",
    "My course speed and destination is …………………………………",
    "Nature of emergency…………………………….",
    "Asistance required",
    "Over",
    "- Ca idee: in RO dist cea mai mare intre doua porturi este intre Capul Midia Navodari si Sf",
    "Gheorghe (50 NM) deci daca esti la jumatate sunt 25 NM deci cam 1 ora pentru SAR ca sa",
    "ajunga la tine si inca o ora ca sa se intoarca la mal. Deci in total 2 ore pentru salvarea unei",
    "victime…..",
   ] },
   { cheie: "z1-resuscitarea-cardiorespiratorie", titlu: "Resuscitarea Cardiorespiratorie", continut: [
    "- Trebuie incepute cat mai rapid pt a dubla sau tripla sansele de supravietuire",
    "- Scop: ca sa mentii creierul in viata",
    "- Interval maxim pt lipsa oxigen la creier fara sechele 3-5 min",
    "- Creierul e cel mai sensibil la lipsa de oxigen",
    "- In 5 minute de anoxie apar leziuni ireversibile (varianta soft e ca isi pierd memoria de scurta",
    "durata si uita ce s-a intamplat in ultimele 24 ore si varianta hard este cand creierul a murit insa",
    "reflexele raman in trunchiul cerebral respiratii si digestie rinichiul merge… dar ramane o planta)",
    "- Respiratia artificiala e ineficienta datorita extensiei inadecvate a capului (nu eliberezi caile",
    "respiratorii suficient)",
    "- Faci masaj cardiac SI respiratie daca nu are puls (la carotida)",
    "- Daca are puls dar nu respira → doar respiratie artificiala",
    "- Daca nu are puls si nici nu respira → faci si respiratie si masaj cardiac",
    "- Resuscitarea cardiopulmonara cu un singur salvator",
    "30 compresii toracice si 2 insuflari pulmonare",
    "Ca sa ajungi la 100 compresii si 6 respiratii per minut.",
    "Etape",
    "Airway – Breathing – Circulation",
    "adica eliberezi caile aeriene (capul pe spate) – respiratia artificiala – masaj cardiac.",
    "Mentii masajul cardiac pana vine salvarea.",
    "In caz de inec primul pas este sa aduci victima intr-o pozitie stabila cu nasul in sus. Apoi pasul",
    "doi este ventilatia artificiala.",
    "Defibrilatorul nu este eficient pentru persoane inecate.",
   ] },
   { cheie: "z1-primul-ajutor-in-caz-de-inec", titlu: "Primul ajutor in caz de inec", continut: [
    "- Intoarcem victima cu fata in sus",
    "- Stare de constienta",
    "- Evaluam daca respira (daca nu respira trebuie scoasa pe mal pentru resuscitare si pot chiar sa",
    "incep respiratie artificiala)",
    "“There is no injury that you can do to the victim by doing CPR that can produce",
    "a more serious condition than death”.",
    "NASCO lifeguard textbook 2017",
    "Adica… daca se rup doua coaste nu prea conteaza. Important e sa ii salvezi viata. Dpdv medical, viata",
    "primeaza asupra membrelor… (life over limb).",
    "Daca nu respira intra in stop cardiac, daca intra in cardiac moare si atunci risc sa ii fac respiratie",
    "artificiala chiar daca suspectez o leziune a coloanei cervicale.",
    "Riscul ca corpii vertebrali sa sectioneze maduva spinarii intrand in focarul de fractura si sa sectioneze",
    "maduva este mult mai mic cand ii faci extensie si dai barbia pe spate decat daca ii pui barbia in piept….",
    "Daca ai in trusa poti folosi pipa Guedel fara sa mai pui capul in extensie. Daca nu ai pipa guedel…. Faci",
    "extensia.",
    "Verifici daca:",
    "- Are puls la carotida ?",
    "- Respira ?",
    "- anunti canal 16 sau 112",
    "- respiratie artificiala",
    "- masaj cardiac",
    "- continua (de preferat peste 100 masaje per minut si 3 respiratii)",
   ] },
   { cheie: "z1-defibrilare", titlu: "Defibrilare", continut: [
    "- fara contact cu alta persoana in timpul analizei aparatului si a defibrilarii propriuzise",
    "- de doua tipuri automate sau semiautomate",
    "- dupa defibrilare:",
    "o pozitia laterala de siguranta",
    "o scoatem hainele ude",
    "o acoperi si incalzesti (recipiente cu apa calda la gat, axile si inghinal)",
    "o decesul poate surveni in primele 24 ore dupa resuscitare",
   ] },
   { cheie: "z1-heimlich", titlu: "Heimlich", continut: [
    "Atunci cand:",
    "- nu respira",
    "- nu vorbeste",
    "- nu poate tusi",
   ] },
   { cheie: "z1-plaga-toracica-penetranta-pneumotorax", titlu: "Plaga toracica penetranta / PNEUMOTORAX", continut: [
    "- inseamna o supapa creata la interiorul corpului intre foita plamanului si cutia toracica care va",
    "duce la colapsarea plamanului",
    "- faci o supapa la exteriorul corpului dintr-o folie de plastic lipita pe 3 laturi cu leucoplast care",
    "sa tina in depresine foita plamanului",
   ] },
   { cheie: "z1-stare-de-soc", titlu: "Stare de soc", continut: [
    "- inseamna tensiune arteriala mult prea mica",
    "- 3 cauze pt care scade tensiunea arteriaa",
    "o Infarct miocardic si inima nu mai are putere sa impinga sange",
    "o Pierdere de sange / hemoragie si inima nu mai are ce sa impinga",
    "o Paralizie a vaselor periferice (la soc anafilactic) care fac sa balteasca sangele si inima",
    "nu are ce sange sa impinga (mori in cateva minute)",
    "- Cand scade TA organismul elibereaza o cant mare de adrenalina care",
    "o Produce o constrictie pe vasele mici ca sa aduca sange d ela periferie catre inima (asa",
    "devine pielea palida ca nu mai are sange)",
    "o Adrenalina face ca ritmul cardiac sa creasca (chiar daca nu mai are sange suficient sa",
    "compenseze prin frecventa)",
    "o Creste forta cu care inima pompeaza sange (chiar daca e mai putin sange sa poata fie",
    "trimis mai puternic in sistem)",
    "o Tot din cauza adrenalinei transpiram semn ca corpul incearca sa corecteze socul",
    "hemodinamic (pielea va fi alba rece si umeda)",
    "o Pentru ca nu ai sange suficient catre creier vei ameti si vei avea stare de ameteala",
    "poate chiar lesini",
    "o Creste frecventa de respiratie",
    "o Ai senzatie de sete pentru ca corpul cere lichide sa compenseze o hemoragie",
    "o Stare de panica ai senzatie de moarte iminenta",
    "o Cand se agraveaza lucrurile si sangele nu mai oxigeneaza suficient creierul… lesini, iti",
    "pierzi cunostinta.",
   ] },
   { cheie: "z1-hemostaza", titlu: "Hemostaza", continut: [
    "- Compresiune locala (cu pansament steril)",
    "- Compresiune digitala la distanta (tehnici speciale de comprimare a arterelor)",
    "- Aplicare garou",
    "Praf hemoragii: CELOX",
   ] },
   { cheie: "z1-soc-anafilactic", titlu: "Soc anafilactic", continut: [
    "- Este paralizia a vaselor de sange periferice care face sa balteasca sangele in acestea si inima",
    "nu are ce sange sa mai impinga (mori in cateva minute)",
    "- Nu are timp claritine si romergan sa isi faca efectul pt ca e vorba de minute",
    "- Se administreaza cortizon sub forma de puf bucal sau pixuri de adrenalina (epipen) =",
    "Adrenalina face vasoconstrictie pe vasele periferice si aduce sangele catre inima, creste",
    "frecventa si puterea de constrictie si singura zona in care se face vasodilatatie e in creier si se",
    "favorizeaza irigatia creierului.",
   ] },
   { cheie: "z1-in-trusa-medicala", titlu: "IN TRUSA MEDICALA", continut: [
    "- Emetostop (rau de mare)",
    "- Alcalinizant",
    "- Acid tramexanic (pt hemostaza) (sau tehnici manuale)",
    "- Imodium (diaree)",
    "- Apotel (paracetamol)",
    "- Salospir (aspirina cardio)",
    "- Pensodril (atac de cord)",
    "- Factor de protectie UV",
    "- Colir (picaturi de ochi)",
    "- Alta medicatie medicala personala.",
   ] },
  ],
 },
 {
  zi: 2, instructor: "Sorin Drugan", titlu: "Manevra navei in condiții speciale", data: "17.10.2023",
  intro: [],
  subiecte: [
   { cheie: "z2-barci-de-emigranti", titlu: "Barci de emigranti", continut: [
    "- In principiu trebuie sa ii salvezi",
    "- Aspecte de analizat:",
    "o Sa nu te arunce pe tine peste bord",
    "o Te mai primesc autoritatile in port? Emigrantii nu sunt pe crewlist… (dar cum “avem",
    "grija”??)",
    "o De multe ori se mai si speculeaza situatiile care implica emigrantii cu scopul de a te",
    "forta sa ii duci la mal",
   ] },
   { cheie: "z2-piraterie", titlu: "Piraterie", continut: [
    "- Exista zone periculoase (golf Aden, marea Arabiei, Marea Rosie, coasta Albaniei etc)",
    "- Se fura mai ales daca pleci de pe barca in zonele cu tari sarace",
    "- Incercati sa negociati, nu incercati sa va impuneti cu forta",
    "- Sunt inarmati",
    "- Nu ezita sa te impuste",
    "- Au un scop precis de a lua / prada cat mai mult",
    "- Se ascunde (daca puteti) echipamentul de valoare (gps, portabila, bani etc)",
    "- Adopti o atitudine mai umila",
    "- Incerci sa negociezi",
    "- Poti sa ai “dummy wallet” cu bancnote mici si CC expirate",
   ] },
   { cheie: "z2-mayday", titlu: "MAYDAY", continut: [
    "- Se da doar cand situatia o cere",
    "- Pe ocean VHF nu e functional ci doar EPIRB sau satelit",
    "- Peste 500 NM poti fi salvat doar de navele care trec prin zona sau nave militare (esti our of",
    "range for helicopters)",
    "- Pentru receptie, intai astepti cel putin 5-10 minute sa vezi daca nu confirma Statia de Coasta,",
    "Abia dupa aceea intervii si fie faci relay fie interrvii daca este aproape de tine.",
   ] },
   { cheie: "z2-navigatie-solitara", titlu: "Navigatie solitara", continut: [
    "- Barca trebuie sa fie pregatita pt navigatie solitara",
    "- Barca trebuie sa fie potrivita pt asa ceva (nici prea mica nici prea mare 11-13 m)",
    "- Necesar autopilot de vant – hydrovane (cel de electronic nu e bun pentru ca nu face fata la",
    "valuri mari si vant puternic)",
    "- Mare atentie la boli si accidente caci… esti singur! Nu va avea cine sa te ajute",
    "- Ideal de a fi facuta in perioada 30-50 ani din motive evidente",
    "- Timing de veghe (ex: 2h)",
   ] },
  ],
 },
 {
  zi: 3, instructor: "Ovidiu Drugan", titlu: "Manevra navei in condiții speciale", data: "18.10.2023",
  intro: ["Nu s-a discutat despre:", "- Obstacole in apa", "- Instalatii defecte (gatit, sanitare, dus)", "- Rau de mare excesiv"],
  subiecte: [
   { cheie: "z3-esuarea", titlu: "Esuarea", continut: [
    "- Apare de obicei atunci cand te duci spre mal in apropierea marinelor si prea putin in mijlocul",
    "marii",
    "- Exista esuare voluntara (dar mai ales la barcile cu motor si nu la veliere)",
    "- Primul lucru se strang velele",
    "- Pornim motorul cat de repede poti si dai inapoi pe unde ai venit",
    "- Daca nu se intampla nimic, puneti echipajul sa stea pe un bord cat mai in exterior pentru a",
    "banda barca cat de mult pori pe bordul respectiv (poti sa te ajuti de bagajele echipajului sau",
    "deschizi ghiul pe partea utila si agati echipajul de el. Dai motor turatie serioasa ca sa poti iesi.",
    "- Daca metodele de mai sus nu dau randament, suni dupa ajutor.",
   ] },
   { cheie: "z3-motor-nefunctional-alte-defectiuni-mecanice", titlu: "Motor nefunctional / alte defectiuni mecanice", continut: [
    "- Atunci cand se intampla ramai fara guvernare",
    "- Primul lucru pe care il faci, ridici velele INSTANTANEU pentru ca iti trebuie urgent un alt mijloc",
    "de propulsie pt a asigura guvernarea. Deschizi focul ca e cel mai rapid. Apoi te duci unde poti,",
    "spre o marina si acolo chemi mecanici sau alte mijloace.",
    "- Nu se fac manevre de acostare la vele. Duci barca pana in gura portului si acolo ceri ajutor!!!!",
    "- Daca esti aproape de mal:",
    "o Puneti oricum toate fenderele in pozitie",
    "o Nu te apropii mai putin de 5 m de mal…",
    "o Faci o bandula din cea mai subtire parama pe care o gasesti la bord, ii legi o greutate",
    "la un capat (fara sa killeresti omul care o prinde) si apoi o arunci cat de departe poti",
    "5m – 10 m catre cine acorda ajutorul.",
    "- Daca nu mai ai motor si nici vele, dai mesaj PAN PAN si anunti defectiunea si solicitarea de",
    "ajutor.",
    "- Daca vantul te duce spre stanci si impactul este iminent iar viata iti este pusa in pericol, dai",
    "MAYDAY.",
   ] },
   { cheie: "z3-timona-rupta-safran-rupt", titlu: "Timona rupta / safran rupt", continut: [
    "- Barca nu mai raspunde la comenzile timonei / cauza poate fi ruperea trotzei (lantul care",
    "actioneaza mecanismul timonei). Atunci apelezi prima oara la eche. Vii la eche pana in",
    "apropiere marinei unde poti cere ajutor.",
    "- Daca cauza este ruperea safranului… daca ai barca sub 30 picioare poti sa inclini barca pentru",
    "schimbarea directiei. Daca barca este mai mare.. eventual poti sa desfaci ghiul si sa il lasi in",
    "spate legat de un balcon si sa ghidezi barca cu el.",
    "- Sau poti sa folosesti ancora de furtuna lasata la pupa si legata cu doua parame astfel incat sa",
    "o folosesti ca pe o carma pentru a schimba directia barcii.",
    "- Daca safranul ramane blocat, este indicat sa cobori in apa si sa incerci sa il deblochezi cu forta",
    "sau chiar sa il rupi.",
   ] },
   { cheie: "z3-pierdere-elice-sau-elice-blocata-de-plase-parame-etc", titlu: "Pierdere elice sau elice blocata de plase / parame etc", continut: [
    "- simptome:",
    "o motorul se tureaza dar barca nu mai inainteaza (nu mai ai elice sau nu mai ai",
    "transmisie)",
    "o motorul se opreste la punerea in sarcina (ai elicea blocata de parama sau plase)",
    "- In acest caz ar trebui sa te bagi in apa sa eliberezi elicea de eventuale plase sau parame.",
    "Scufundarea se face cu cutitul “in dinti” si neaparat legat de o sfoara pt ca sigur iti va scapa.",
    "- Daca ai pierdut elicea de tot ridici velele si vii pana la intrarea in marina si ceri ajutor.",
   ] },
   { cheie: "z3-incendiu-la-bord", titlu: "Incendiu la bord", continut: [
    "- Prerechizite: temperatura (necesara aprinderii), carburant (ce sa arda, materialul inflamabil),",
    "oxigen (ca sa intretina arderea). Daca lipseste oricare dintre aceste componente, focul nu",
    "poate exista.",
    "- Cauze: bucatarie, motor, electric (scurtcircuite, contacte), butelie de gaz.",
    "- Incendiul la bord e unul dintre cel mai prost lucru care se poate intampla. Intre foc si apa nu",
    "prea ai scapare…",
    "- Cel mai rau e sa fii cu prova in vant pt ca arderea va aduce tot fumul in cockpit. Este indicat sa",
    "arunci ancora de furtuna si sa tii barca cu pupa in vant ca fumul sa se duca in prova sa nu",
    "asfixiezi tot echipajul.",
    "- Trebuie sa existe extinctoare la bord, sa stie toata lumea cum se folosesc.",
   ] },
   { cheie: "z3-ancora-agatata-de-pietre-alta-ancora", titlu: "Ancora agatata de pietre / alta ancora", continut: [
    "- Daca ai agatat ancora de ancora altuia, o ridici. Vei observa ca vinciul merge greu si lantul barcii",
    "din fata clantane. El va simti acest lucru. Eventual il rogi sa slabeasca putin ancora pentru a nu",
    "avea lantul in tensiune. Continui sa ridici lantul tau pana cand ancora ta iese din apa sau e cam",
    "la suprafata. Se trece o parama pe sub lantul lui si se leaga la tachetul tau cu ambele capete",
    "pentru a prelua greutatea lantului lui. Dai ancora ta jos, lantul lui ramanand in parama legata",
    "la tachet. Ai eliberat ancora ta si o treci pe sub lantul lui. Apoi desfaci de la tachet ferindu-ti",
    "gherele de parama care se va desfasura destul de aprig sub greutatea lantului lui. Apoi il anunti",
    "ca ai terminat si el ar trebui sa isi intinda din nou lantul de la ancora pentru a ramane in pozitie.",
    "- Daca ai agatat ancora de o piatra, poti sa astepti minimul unui val si sa mai recuperezi din lant.",
    "Vei folosi apoi flotabilitatea urmatorului val care va ridica barca si va trage de lantul ancorei.",
    "Daca nu iese, inseamna ca e prea tare agatata si va trebui sa incerci sa schimbi unghiul sub",
    "care tragi de ancora (tragi cu pupa in diverse directii si speri ca sub unul din unghiuri o va",
    "elibera).",
    "- Daca tot nu se elibereaza ancora, poti alege sa tai lantul si o declari pierduta fie dai drumul de",
    "lant si pui fendere separate si legate separat de verigi de lant separate ca marker. Te duci in",
    "prima marina, iei un scafandru si scoti ancora (dar nu pierzi garantia pe barca). Un lant e 800",
    "EUR varful si apoi 50 eur fiecare metru de lant. Un scafandru costa cam 150 EUR…",
   ] },
   { cheie: "z3-gaura-de-apa-parasirea-navei", titlu: "Gaura de apa / Parasirea navei", continut: [
    "- Gaura de apa poate aparea in urma unei ciocniri sau ex: desfacerea unei tevi de la webasto,",
    "sau o valva de wc, sau instrumentul de viteza desurubat.",
    "- Simptome: se umple cu apa, gasesti apa in barca.",
    "- Primu lucru o gusti. Daca e dulce e de bine. Daca e sarata e de rau. Apoi pornesti pompa de",
    "santina si vezi ca merge. Urmaresti nivelul. Daca scade nivelul e ok. Daca nu…",
    "- Cauti gaura de apa pana o gasesti. Vezi daca o poti repara, pui un dop, o infunzi. Scoti",
    "apa.Folosesti pompa de santina manuala. Daca nu merge pui oamenii sa scoata cu ghiordelul.",
    "- Daca nivelul incepe sa scada, inseamna ca poti sa tii situatia sub control.",
    "- Daca nu o gasesti…. Problem.",
    "- Parasesti nava. Liferaft / Pluta de salvare, mesaj de mayday, organizat iesirea, mutat oamenii,",
    "- Ar fi bine sa existe un “grab bag” cu toate cele necesare (acte, apa, glucoza, baterie externa,",
    "telefon, flares, lucruri esentiale etc)",
    "OBS: Pentru eliberarea unui nou pasaport temporar, ai nevoie macar de o copie a certificatului",
    "de nastere. Deci ar fi indicat sa ai pe mobil copii ale actelor personale printre care si a cert de",
    "nastere.",
   ] },
   { cheie: "z3-instrumente-nefunctionale-black-ship", titlu: "Instrumente nefunctionale / black ship", continut: [
    "- Barca devine black ship cand nu mai are suficient curent in baterii, cand barca consuma mai",
    "mult curent decat poate produce.",
    "- Ajungi sa nu mai ai lumini, nu mai ai comunicatii, nu mai ai telefonae nu mai ai nimic nimic.",
    "- Se foloseste navigatia celesta (trebuie sa stii mereu un astru care iti poate indica directia utila)",
    "- Mitigation:",
    "o reducerea consumului de curent electric,",
    "o fara toalete electrice",
    "o frigiderul oprit",
    "o audio pa paaa",
    "o telefoanele se vor folosi doar cate unul la un moment dat si intermitent doar pe modul",
    "avion, si doar pentru a verifica directia pe care merg.",
   ] },
   { cheie: "z3-lipsa-lumini-de-navigatie", titlu: "Lipsa lumini de navigatie", continut: [
    "- foarte importante la intoarcerea seara in marina",
    "- devii pericol pentru ceilalti care nu te vad",
    "- pui o lanterna pe vela",
   ] },
   { cheie: "z3-catarg-rupt", titlu: "Catarg rupt", continut: [
    "- de multeori se rupe in vant slab (uzura)",
    "- Daca se rupe un sart, cobori imediat toate velele si folosesti o funga sa tensionezi putin catargul",
    "pe partea sartului rupt si vii urgent la mal intr-o marina pt reparatii.",
    "- Catargul rupt nu se duce la fund. Are prea multe straiuri si sarturi etc. El ramane in proximitatea",
    "barcii. Aduceti si descurcati catargul si aduceti-l dealungul barcii la bord.",
    "- Daca e furtuna si devine periculos sa gaureasca barca, atunci trebuie sa tai paramele si velele",
    "si sa tai sarturile cu clestele de sarturi. Ai fungi si scote atat pe exteriorul catargului dar ai si pe",
    "interiorul catargului. Ai si cabluri electrice si o intreaga invalmaseala.",
   ] },
   { cheie: "z3-vele-rupte", titlu: "Vele rupte", continut: [
    "- Velele rupte = steagul rusinii",
    "- Te pui in vant, dai vela jos, prinzi funga jos, o impachetezi, cauti alta vela, te duci la mal cu ce",
    "mai ai.",
    "- “Nu exista vant prea puternic ci vele prea mari”. Daca ti s-a rupt vela inseamna ca ai tinut-o",
    "deschisa cand nu era cazul sau nu ai inchis-o la timp.",
    "- O vela e pe al 2500 EUR deci iti executa toata garantia.",
   ] },
   { cheie: "z3-traznet", titlu: "Traznet", continut: [
    "- Destul de rar",
    "- Protejezi echipamentele de navigatie",
    "- Disconnect shore power",
   ] },
   { cheie: "z3-coliziune", titlu: "Coliziune", continut: [
    "- Dupa izbitura, verifici daca echipajul este in regula",
    "- Te duci sa vezi ce e in zona in care te-ai lovit pe sus",
    "- Te duci jos si vezi daca ai apa, ridici si vezi la cel mai jos punct daca creste nivelul apei. Daca nu",
    "creste nivelul apei e bine, chiar daca pe afara arata naspa cu balcoane rupte etc.",
    "- Daca izbitura e in apa, trebuie sa verifici sub apa daca chila e ok chiar si noaptea sa verifici daca",
    "nu ai gaura de apa.",
   ] },
   { cheie: "z3-pierdere-de-documente", titlu: "Pierdere de documente", continut: [
    "Le declari:",
    "- La ambasada / consulat",
    "- La charterist si pierzi toata garantia",
   ] },
   { cheie: "z3-nava-arestata", titlu: "Nava arestata", continut: [
    "- Se urmareste procedura legala",
    "- Sau se incearca sa se negocieze cu ei",
    "- Acoperiti-va de dovezi",
    "- Black Charter = daca faci activitate comerciala, ai luat bani si nu ai declarat activitatea este",
    "motiv de nava arestata",
   ] },
   { cheie: "z3-om-la-apa", titlu: "Om la apa", continut: [
    "- Exista o procedura specifica. Se atribuie roluri, cine il vede striga “Om la apa!” Apoi tine mana",
    "intinsa catre el pentru ca skipperul sa il poata vedea oricand. Se arunca colacul de salvare, se",
    "poate arunca parama la pupa, skipperul intoarce barca si se incearca recuperarea.",
    "- Daca nu e la vedere dai MAYDAY, last known position, si de atunci viata lui depinde de cine il",
    "poate salva…",
    "- Nu exista scena mai oribila decat sa cazi tu ca skipper in apa si sa vezi barca nu se duce….",
    "- Noaptea stati mereu ca hamul cuplat.",
    "- Panica se instaleaza foarte repede.",
    "- Manevra se face cu motor, se strange focul sau il lasi sa fluture.",
    "- Se foloseste cangea sau parame sau orice ai pentru recuperare.",
   ] },
   { cheie: "z3-oboseala-cronica", titlu: "Oboseala cronica", continut: [
    "- In mod normal nu ar trebui sa apara",
    "- Simptomatologie: cand mergi de 3-4 zile, carturile nu s-au respectat si ajungi efectiv sa delirezi.",
    "Creierul isi da shut down si gata.",
    "- Mitigation: trebuie sa incerci sa te inlocuiesti. Pui autopilot sau pe cineva sa supravegheze",
    "cursul si te duci sa dormi 2 – 3 ore.",
    "- De ex nu pleci pana la Istambul in 3 oameni. E prea istovitor. Ar trebui 5-6 oameni.",
    "- Exista oboseala fizica, si oboseala psihica. Somnul REM e pt oboseala psihica care dureaza 15",
    "min iar celalalt e pentru oboseala fizica. Managementul oboselii ar trebui sa asigure 15-20 min",
    "de somn (juma de ora) pentru recuperarea macar a oboselii psihice.",
    "- Nu rezisti → nu faci cart.",
    "- Oboseala infrange orice instinct.",
    "- Nu va jucati!! Creierul isi da shut down fara sa poti face ceva… visezi cu ochii deschisi…",
   ] },
   { cheie: "z3-furtuna-medicane-bora-meltemi", titlu: "Furtuna - Medicane / Bora / Meltemi", continut: [
    "- Sunt fenomene de vant foarte puternic",
    "- Nu e cel mai groaznic lucru care se poate intampla ba chiar e mai mult inconfortabila",
    "- Provoaca panica, teama, disconfort, rau de mare dar se poate gestiona",
    "- Trebuie sa te pregatesti, sa reduci velele, sa inchizi geamurile, sa nu mergi de-a latul valurilor",
    "sa nu iti rupa carma etc",
    "- Trebuie sa ai vesta de salvare, ochelari, haine potrivire, usile si geamurile inchise, motorul in",
    "functiune, velele tertarolate la minim TREBUIE SA REZISTI!!",
    "- Te pui la adapost: pui o insula intre tine si vant, te apropii de insula la cativa metri si nu o sa",
    "mai ai val. Sigur o sa ai vant, dar esti la adapost.",
    "- Sau mergi intr-o marina la adapost.",
    "- Sau fugi de furtuna cu vant de mare larg…",
    "- Barca va rezista!",
    "- Greseli:",
    "o Nu se tertaroleaza la timp. Daca vezi nori negrii tertarolezi.",
    "o Nu se imbraca lumea la timp. Ploaia vine cu vant rece. Nu o sa mai vrei sa cobori in",
    "barca pe timp nefavorabil.",
    "- Aceste vanturi sunt prognozate (adica sunt predictibile) Trebuie sa fii destul de abil sa nu te",
    "prinda aceste fenomene.",
    "- In Grecia cand vanturile sar de 25 Kt la vant ei nu mai pot prognoza corect si de fapt sunt mai",
    "mult de atat. Ex. In Cyclade cand sunt anuntate 28 Kt vant de fapt sunt 36 Kt sau 40-45 Kt de",
    "vant real.",
    "- In cartea pilot se mentioneaza gradul de protectie pentru Bora sau Meltemi.",
   ] },
   { cheie: "z3-combustibil-terminat", titlu: "Combustibil terminat", continut: [
    "- Motorul se opreste sau se supratureaza sau variaza intre aceste simptome.",
    "- Daca barca bandeaza motorul poate trage aer. Daca barca bandeaza 35-45 grade nu ar trebui",
    "saai motorul pornit ca ai vant.",
    "- Ridici velele si mergi la vele si apoi ceri ajutor pentru rezerva de combustibil",
    "- Atentie cu dinghy – daca se termina combustibilul la dinghy e aproape imposibil de manevrat",
    "impotriva vantului sau curentului.",
    "- Un velier nu ar trebui sa plece niciodata nicaieri fara cel putin 1/3 din rezervor (o treime!)",
    "- O barca cu motor nu ar trebui sa plece fara ¾ din rezervor (3 sferturi!)",
   ] },
   { cheie: "z3-remorcaj", titlu: "Remorcaj", continut: [
    "- Cand sunt valuri doua barci nu pot sta una langa cealalta (!!) si atunci se face remorcaj la",
    "parama lunga (fata / spate)",
    "- Parama se leaga in cross (tachetul pupa tribord la tacehtul prova babord).",
    "- Parama trebuie sa fie lunga sau foarte lunga.",
    "- Daca barca remorcata e mai mare decat a ta, legi o parama la tine de cei doi tacheti pupa si",
    "parama lui sa faca un Y cu a ta.",
    "- Daca trebuie sa innozi doua parame, faci mai degraba doua noduri de gasa la fiecare decat",
    "nodul de impreunare.",
    "- Trebuie sa existe control al timonele fiecarei barci obligatoriu.",
    "- Oprirea se face treptat pt ca barca remorcata nu are frana…",
    "- Sau cand ajungi in marina te treci langa barca remorcata si te tragi la urechi cu paramele la PIC",
    "ca sa poti sa dai drumul rapid.",
    "- Deci doua metode:",
    "o La remorca sau",
    "o la ureche (niciodata pe valuri)",
    "- Daca intre cele doua veliere este o diferenta prea mare, apar probleme enorme.",
    "TO ASK:",
    "CARE E ZONA DE DEMAGNETIZARE LA LIMANU?",
    "DENUMIRI ALE ZONELOR LIMANU? (ex “doua dane”… “bazinul mare”)",
    "DATE DE CONTACT MARINA LIMANU? (telefon, canal comunicatie, pers de contact)",
   ] },
   { cheie: "z3-provizii-terminate", titlu: "Provizii terminate", continut: [
    "- Alimentatia buna pastreaza moralul ridicat la tot echipajul de pe barca",
    "- Ex: mirosul de pane coapta pe barca ridica moralul chiar daca esti plecat de mult timp",
    "- Faina si drojdia si sarea se pastreaza in sticle de plastic inchise cu dop. Ingredientele pot fi si",
    "amestecate apriori si cand vrei sa le folosesti sunt gata de amestecat cu apa si gata.",
    "- Cand iti dai seama ca ramai fara provizii Rationalizezi, mananci calculat",
    "- Se intampla mai frecvent decat credeti datorita estimarii eronate a proviziilor necesare (apa,",
    "mancare). Foamea apare chiar si la plimbari scurte. Marea face foame si sete, mai ales daca e",
    "si cu innotat.",
    "- E bine sa ai cate o ciocolata aruncata pe acolo, mars, snickers, chestii de rontait.",
   ] },
   { cheie: "z3-epidemii-pe-barca", titlu: "Epidemii pe barca", continut: [
    "- Daca e cazul e posibil sa fii carantinat si sa ai chiar si jandarm la barca ca nu cumva sa cobori",
    "pe insula (vezi cazul din Poros cand cineva a fost identificat cu covid. Au stat 14 zile pe barca",
    "cu toate consecintele rezultante – bilete de avion testare etc).",
    "- Ar trebui sa declari la cea mai apropiata unitate medicala si probabil iti iei crantina pe barca",
   ] },
   { cheie: "z3-furtuna-in-marina", titlu: "Furtuna in marina", continut: [
    "- In marina teoretic e adapost cu barca legata… totusi uneori exista niste conditii care creaza",
    "furtuna in marina. Ce faci?",
    "Mitigation:",
    "- Se pun barcile 1 din 2 mai in fata si mai un spate pentru ca la balansarea catargului sa nu se",
    "loveasca unul cu altul (catargele sa nu mai fie in linie)",
    "- Se da drumul la motor pe pozitia inainte pentru a te tine in tensiune pe paramele de la pupa",
    "si a elibera tensiunea pe ancora.",
    "- Pui fendere suplimentare",
    "- Stai de veghe continua",
   ] },
   { cheie: "z3-marina-aglomerata-pana-la-refuz", titlu: "Marina aglomerata pana la refuz", continut: [
    "- Sa ai mereu un backup plan (ancora, schimbat marina, alegi un golf sau te legi prova in pupa",
    "la dublin)",
    "- Sa ai mereu managementul oboselii (daca trebuie sa pleci imediat sa si poti sa faci asta)",
    "- Prova in pupa e cea mai buna asezare pentru ca nu ai contact intre barci.",
   ] },
   { cheie: "z3-ancoraj-pe-vreme-rea", titlu: "Ancoraj pe vreme rea", continut: [
    "- Alege un loc sub vant dar atentie sa nu se roteasca vantul ca te duce in stanci",
    "- Lasa toata ancora",
    "- Sa stai pe directia vantului",
    "- Sa nu ai valuri",
   ] },
   { cheie: "z3-frig-excesiv", titlu: "Frig Excesiv", continut: [
    "- Frigul este o stare de disconfort, atrage rau de mare, atrage somnolenta si stare de panica",
    "- Frigul e mana in mana cu umezeala",
    "- Pe barca mai uitam niste geci. Le numim geci tehnice pentru cei care nu isi iau de imbracat.",
    "- Noaptea se face frig pe mare, chiar daca ziua e bine",
    "- Apa “suge” caldura din corp foarte tare",
    "- Nu asteptati sa intre frigul in tine ci echipeaza-te din timp",
    "- Caldura corporala se pierde foarte mutl prin cap si gat",
    "- E foarte greu sa revii la frig dupa ce te-ai incalzit",
    "- Sub 10 grade C trebuie sa va alertati. Pana la 10 grade corpul poate sa isi produca caldura",
    "necesara. Sub 10 grade nu mai poate face acest lucru.",
    "- Cel mai bine sa ai caldura activa in cabina – webasto sau AC.",
   ] },
   { cheie: "z3-poluarea-apei-provocata-de-noi", titlu: "Poluarea apei provocata de noi", continut: [
    "- Skiperii sunt ecologisti prin definitie. Incercam sa nu poluam apa. Minimizam poluarea apelor.",
    "- Nu aruncam plastic sau alte lucruri in apa",
    "- Puteti anunta poluarile apei (pelicule pe apa)",
    "- Ape nerge = nr 2 de la wc",
    "- Ape gri = nr. 1, dus si spalatul vaselor",
    "- Bio pot fi aruncate in apa, ce este plastic se aduce la mal.",
   ] },
   { cheie: "z3-vizibilitate-redusa", titlu: "Vizibilitate redusa", continut: [
    "- Cel mai periculos fenomen meteo (mai periculos decat furtuna)",
    "- Are si impact psihic profund, te simti pierdut efectiv, ajungi sa nu mai crezi nici aparatele",
    "- Poate induce dezorientare grava, neincredere, anxiozitate",
    "- Viteza mica + Aparate + Sunet (Ascultare + fluier)",
    "- Vezi COLREG cu semnale sonore pe timp de ceata",
   ] },
   { cheie: "z3-conflict-intre-membrii-echipajului", titlu: "Conflict intre membrii echipajului", continut: [
    "- Poate fi: echipaj vs skipper // skipper vs coskipper // skipperi de pe doua barci",
    "- Ca skipper trebuie sa mediezi, sa aplanezi cat poti cat mai fin cu diplomatie, psihologie",
    "- Multe conflicte pot fi aplanate daca la briefing pui regulile jocului cat mai bine) vezi problemele",
    "din Cyclade de crew management!!).",
    "- Nu abuzati de puterea data de functia de skipper (pt ca asa zic eu)",
    "- Trebuie sa stii cand sa lasi de la tine atunci cand se poate lasa de la tine",
    "- Daca se cearta skipper si coskipper de obicei se lasa cu fiecare va pleca pe barca lui si nu se vor",
    "mai intalni la comanda. Fiecare cu mandria lui. La fel si intre doi skipperi de la doua barci. Daca",
    "sunt prieteni… poate va trece dar de obicei se vor seta lucrurile in sensul asta.",
    "- Chiar si anuntarea faptului ca intr-o saptamana de Cyclade exista Miercurea neagra (cand",
    "exista asteptarea ca echipajul sa se certe) duce foarte fin la aplanarea conflictelor care pot",
    "aparea pentru ca echipajul deja se asteapta sa se certe si vor incerca inconstient sa aplaneze",
    "asteptarile de Miercuri.",
   ] },
   { cheie: "z3-terminarea-bauturii-la-bord", titlu: "Terminarea bauturii la bord", continut: [
    "- Ori se termina bautura de la bord pe bune si iese cearta",
    "- Ori prea multa bautura duce la conflict si cafteli pe bord",
    "- Bautura de la bord cel mai bine e sa fie moderata",
    "- Cel mai bine e ca skipperul sa nu bea….",
    "- Nici conceptul de dry ship nu e prea bun (adica sa nu existe bautura deloc pe barca)",
   ] },
  ],
 },
]

export const TOATE_SUBIECTELE = CURS_B.flatMap(z => z.subiecte)
